### ISSUE TITLE
[FIX] Root page 랜더링 딜레이 이슈 

### ISSUE THREAD

**Issue by 5kdk** [5kdk/QnA-Box#116]
## 핵심 구현 타이틀
AppShell 로그인 확인 로직 위치이동

## 해당 기능을 구현하기 위해 할 일
- [ ] todo1
- [ ] todo2

**Comment by YUNH7** [comment]
가드로 옮기면 가드가 안씌워진 페이지에서는 자동로그인이 안될 거예요

일단 덜 눈에 띄게 Appshell에서 root 페이지일 경우 배경색 검정색되도록 변경해놓겠습니다

**Comment by 5kdk** [comment]
@YUNH7  코멘트 확인했습니다. 굳이 유저 정보가 필요하지 않은 페이지에서도 유저정보 요청때문에 랜더링이 지연되고있으니 다른 방법을 고민해볼게요! 새로운 pr에도 적용했다가 롤백 했습니다.
